### ISSUE TITLE
static

### ISSUE THREAD

**Issue by F4kogLc** [ImAxel0/IL2CPP_Scanner_Reborn#1]
how to inspect static classes, not mono behs? is this feature planned?

**Comment by ImAxel0** [comment]
I made this but I'm not really familiar with c#. Are those classes which don't inherit from MonoBehaviour or any other class? I thought it would find all classes in the defined module.

**Comment by F4kogLc** [comment]
yes, like this, classes which don't inherit from MonoBehaviour

![image](https://github.com/ImAxel0/IL2CPP_Scanner_Reborn/assets/77386323/f9624c0d-23d0-4205-ba42-a6e980fac949)

**Comment by ImAxel0** [comment]
What game is it? Could you suggest me a game with a static class to search so I can look into it? I normally use Sons of the Forest to test things out but most classes are inherited from mono. Anyway I only see one function to fetch classes in il2cpp resolver and it's the one I use so I doubt I can do anything about it.

**Comment by F4kogLc** [comment]
try this game
https://store.steampowered.com/app/1013320/Firestone/

**Comment by ImAxel0** [comment]
Ok I tried and couldn't find any class which doesn't inherit from another class. I don't know if it's because they aren't enabled in that moment or if it's a il2cpp resolver limitation. As I said earlier I only know one function to search for classes in il2cpp resolver so I really don't know where to start and probably won't be solved, sry.
